[package]
name = "kernels"
version = "0.3.0"
edition = "2021"
description = "Paged attention kernels for Rust"
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]

[build-dependencies]
cudaforge = { git = "https://github.com/guoqingbao/cudaforge.git", version= "0.1.0", rev = "5940f46"}
anyhow = { version = "1", features = ["backtrace"] }

[features]
no-marlin = []
no-fp8-kvcache = []
cutlass = []
